/** Actions that can be granted per module in the permission system */
export enum ActionEnum {
  Create = 1,
  View = 2,
  Update = 3,
  Delete = 4,
  Search = 5,
  Confirm = 6,
  Approve = 7,
  Reject = 8,
  Receive = 9,
  Verify = 10,
  Delivery = 11,
  Assign = 12,
  Forward = 13,
  Lock = 14,
  UnLock = 15,
  Adjust = 16,
  Complete = 17,
  Hold = 18,
  Close = 19,
  Open = 20,
  ReOpen = 21,
}
