export enum RelationEnum {
  Father = 1,
  Mother = 2,
  Sister = 3,
  Brother = 4,
  Uncle = 5,
  Aunt = 6,
  GrandFather = 7,
  GrandMother = 8,
  FatherInLaw = 9,
  MotherInLaw = 10,
  BrotherInLaw = 11,
  SisterInLaw = 12,
  Husband = 13,
  Wife = 14,
  Son = 15,
  Daughter = 16,
  Relative = 17,
  Friend = 18,
  Classmate = 19,
  Roommate = 20,
  Others = 21,
}
